name: BunnyX Kernel Build

on:
  push:
    branches:
      - mcqueen-ksu

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: mcqueen-ksu
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential curl flex git \
            libssl-dev lzop python3 zip unzip \
            gcc g++ clang lld ccache

      - name: Grant execute permission
        run: chmod +x build.sh

      - name: Build kernel
        run: ./build.sh

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: BunnyX-Kernel
          path: AnyKernel3/*.zip
